# Generated by Django 5.0.3 on 2026-04-19 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("warning_system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterventionRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("talk", "谈心谈话"),
                            ("academic", "学业帮扶"),
                            ("psychological", "心理疏导"),
                            ("family", "家校联系"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="干预类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="干预标题"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="干预内容详情"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="干预方式"
                    ),
                ),
                (
                    "result",
                    models.TextField(blank=True, null=True, verbose_name="干预结果"),
                ),
                (
                    "is_effective",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(0, "无效"), (1, "有效"), (2, "待评估")],
                        null=True,
                        verbose_name="是否有效",
                    ),
                ),
                (
                    "follow_up_needed",
                    models.SmallIntegerField(default=0, verbose_name="是否需要跟进"),
                ),
                (
                    "follow_up_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="计划跟进时间"
                    ),
                ),
                ("intervention_time", models.DateTimeField(verbose_name="干预时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "干预记录",
                "verbose_name_plural": "干预记录",
                "db_table": "intervention_records",
                "ordering": ["-intervention_time"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SMSNotification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(max_length=20, verbose_name="接收手机号")),
                ("content", models.TextField(verbose_name="短信内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("delivered", "已送达"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送达时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        db_column="sender_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_sms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_sms",
                        to="classes.student",
                        verbose_name="接收学生",
                    ),
                ),
                (
                    "warning",
                    models.ForeignKey(
                        blank=True,
                        db_column="warning_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_notifications",
                        to="warning_system.warningrecord",
                        verbose_name="关联预警",
                    ),
                ),
            ],
            options={
                "verbose_name": "短信通知",
                "verbose_name_plural": "短信通知",
                "db_table": "sms_notifications",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
    ]
