# Generated by Django 5.0.3 on 2026-04-11 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Counselor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_no",
                    models.CharField(
                        db_column="employee_no",
                        max_length=20,
                        unique=True,
                        verbose_name="工号",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        db_column="department",
                        max_length=100,
                        null=True,
                        verbose_name="所属院系",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_column="phone",
                        max_length=20,
                        null=True,
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "office",
                    models.CharField(
                        blank=True,
                        db_column="office",
                        max_length=100,
                        null=True,
                        verbose_name="办公地点",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", verbose_name="更新时间"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "辅导员信息",
                "verbose_name_plural": "辅导员信息",
                "db_table": "counselors",
                "ordering": ["employee_no"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_no",
                    models.CharField(
                        db_column="teacher_no",
                        max_length=20,
                        unique=True,
                        verbose_name="工号",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        db_column="department",
                        max_length=100,
                        null=True,
                        verbose_name="所属院系",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_column="title",
                        help_text="教授/副教授/讲师/助教等",
                        max_length=50,
                        null=True,
                        verbose_name="职称",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_column="phone",
                        max_length=20,
                        null=True,
                        verbose_name="办公电话",
                    ),
                ),
                (
                    "office",
                    models.CharField(
                        blank=True,
                        db_column="office",
                        max_length=100,
                        null=True,
                        verbose_name="办公室位置",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", verbose_name="更新时间"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师信息",
                "verbose_name_plural": "教师信息",
                "db_table": "teachers",
                "ordering": ["teacher_no"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_no",
                    models.CharField(
                        blank=True,
                        db_column="employee_no",
                        max_length=20,
                        null=True,
                        verbose_name="学号/工号",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        db_column="department",
                        max_length=100,
                        null=True,
                        verbose_name="所属院系/班级",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_column="phone",
                        max_length=20,
                        null=True,
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", verbose_name="更新时间"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户扩展信息",
                "verbose_name_plural": "用户扩展信息",
                "db_table": "user_profiles",
                "managed": True,
            },
        ),
    ]
