# Generated by Django 5.0.3 on 2026-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentCourseScore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "attendance_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="出勤率",
                    ),
                ),
                (
                    "video_progress",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="视频进度",
                    ),
                ),
                (
                    "homework_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="作业平均分",
                    ),
                ),
                (
                    "homework_submit_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="作业提交率",
                    ),
                ),
                (
                    "exam_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="考试平均分",
                    ),
                ),
                (
                    "knowledge_mastery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="知识点掌握度",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="期末成绩",
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(auto_now=True, verbose_name="最后计算时间"),
                ),
            ],
            options={
                "verbose_name": "学生课程综合得分",
                "verbose_name_plural": "学生课程综合得分",
                "db_table": "student_course_scores",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WarningRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("high", "红色预警"),
                            ("medium", "橙色预警"),
                            ("low", "黄色预警"),
                            ("normal", "正常"),
                        ],
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "composite_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="综合得分",
                    ),
                ),
                (
                    "attendance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="出勤率得分",
                    ),
                ),
                (
                    "progress_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="学习进度得分",
                    ),
                ),
                (
                    "homework_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="作业成绩得分",
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="考试成绩得分",
                    ),
                ),
                (
                    "ai_analysis",
                    models.TextField(blank=True, null=True, verbose_name="AI问题分析"),
                ),
                (
                    "ai_suggestions",
                    models.JSONField(blank=True, null=True, verbose_name="AI建议列表"),
                ),
                (
                    "ai_parent_script",
                    models.TextField(
                        blank=True, null=True, verbose_name="AI家长沟通文案"
                    ),
                ),
                (
                    "ai_encouragement",
                    models.TextField(blank=True, null=True, verbose_name="AI激励信"),
                ),
                (
                    "ai_source",
                    models.CharField(
                        choices=[("ai", "AI生成"), ("template", "模板")],
                        default="template",
                        max_length=10,
                        verbose_name="建议来源",
                    ),
                ),
                (
                    "ai_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="AI评语生成时间"
                    ),
                ),
                (
                    "counselor_comment",
                    models.TextField(blank=True, null=True, verbose_name="辅导员评语"),
                ),
                (
                    "counselor_suggestions",
                    models.JSONField(
                        blank=True, null=True, verbose_name="辅导员建议列表"
                    ),
                ),
                (
                    "counselor_talk_script",
                    models.TextField(
                        blank=True, null=True, verbose_name="沟通话术建议"
                    ),
                ),
                (
                    "sms_sent",
                    models.BooleanField(default=False, verbose_name="短信已发送"),
                ),
                (
                    "sms_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="短信发送时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "生效中"),
                            ("resolved", "已解决"),
                            ("ignored", "已忽略"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="预警状态",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "resolve_note",
                    models.TextField(blank=True, null=True, verbose_name="处理备注"),
                ),
                (
                    "calculation_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="计算时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "预警记录",
                "verbose_name_plural": "预警记录",
                "db_table": "warning_records",
                "ordering": ["-calculation_time"],
                "managed": False,
            },
        ),
    ]
