# Generated by Django migration
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    """添加辅导员评语相关字段"""

    dependencies = [
        ('warning_system', '0001_initial'),
    ]

    operations = [
        # 添加AI评语生成时间和生成者
        migrations.AddField(
            model_name='warningrecord',
            name='ai_generated_at',
            field=models.DateTimeField(null=True, blank=True, verbose_name='AI评语生成时间'),
        ),
        migrations.AddField(
            model_name='warningrecord',
            name='ai_generated_by',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.SET_NULL,
                null=True, blank=True,
                db_column='ai_generated_by',
                related_name='generated_ai_comments',
                verbose_name='AI评语生成者'
            ),
        ),

        # 添加辅导员评语字段
        migrations.AddField(
            model_name='warningrecord',
            name='counselor_comment',
            field=models.TextField(null=True, blank=True, verbose_name='辅导员评语'),
        ),
        migrations.AddField(
            model_name='warningrecord',
            name='counselor_suggestions',
            field=models.JSONField(null=True, blank=True, verbose_name='辅导员建议列表'),
        ),
        migrations.AddField(
            model_name='warningrecord',
            name='counselor_talk_script',
            field=models.TextField(null=True, blank=True, verbose_name='沟通话术建议'),
        ),

        # 添加短信通知状态
        migrations.AddField(
            model_name='warningrecord',
            name='sms_sent',
            field=models.BooleanField(default=False, verbose_name='短信已发送'),
        ),
        migrations.AddField(
            model_name='warningrecord',
            name='sms_sent_at',
            field=models.DateTimeField(null=True, blank=True, verbose_name='短信发送时间'),
        ),
    ]
