# Generated by Django 5.0.3 on 2026-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="name", max_length=100)),
                (
                    "grade",
                    models.CharField(
                        blank=True, db_column="grade", max_length=10, null=True
                    ),
                ),
                (
                    "major_id",
                    models.IntegerField(blank=True, db_column="major_id", null=True),
                ),
                (
                    "counselor_id",
                    models.IntegerField(
                        blank=True, db_column="counselor_id", null=True
                    ),
                ),
                (
                    "student_count",
                    models.IntegerField(db_column="student_count", default=0),
                ),
                (
                    "raw_id",
                    models.CharField(
                        blank=True, db_column="raw_id", max_length=50, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "db_table": "classes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="name", max_length=100)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_column="code",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, db_column="department", max_length=100, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "db_table": "majors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "raw_id",
                    models.CharField(
                        blank=True, db_column="raw_id", max_length=50, null=True
                    ),
                ),
                (
                    "student_no",
                    models.CharField(
                        db_column="student_no", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=50)),
                (
                    "class_id",
                    models.IntegerField(blank=True, db_column="class_id", null=True),
                ),
                ("gender", models.SmallIntegerField(db_column="gender", default=0)),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_column="phone", max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="email", max_length=100, null=True
                    ),
                ),
                (
                    "major_id",
                    models.IntegerField(blank=True, db_column="major_id", null=True),
                ),
                (
                    "enrollment_year",
                    models.IntegerField(
                        blank=True, db_column="enrollment_year", null=True
                    ),
                ),
                ("status", models.SmallIntegerField(db_column="status", default=1)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updated_at"),
                ),
            ],
            options={
                "db_table": "students",
                "managed": False,
            },
        ),
    ]
